
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.jigsawponosdlc.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.common.ForgeSpawnEggItem;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.BlockItem;

import net.mcreator.jigsawponosdlc.item.WandOfMassDestructionItem;
import net.mcreator.jigsawponosdlc.item.VacuumCleanerItem;
import net.mcreator.jigsawponosdlc.item.VCDebugPigItem;
import net.mcreator.jigsawponosdlc.item.VCDebugMainItem;
import net.mcreator.jigsawponosdlc.item.VCDebugBadItem;
import net.mcreator.jigsawponosdlc.item.TrusiItem;
import net.mcreator.jigsawponosdlc.item.TelescopesusItem;
import net.mcreator.jigsawponosdlc.item.TazikKostyl1Item;
import net.mcreator.jigsawponosdlc.item.TazikChakramItem;
import net.mcreator.jigsawponosdlc.item.TazikChakramFloppaItem;
import net.mcreator.jigsawponosdlc.item.SweetBreadRangedItem;
import net.mcreator.jigsawponosdlc.item.SweetBreadItem;
import net.mcreator.jigsawponosdlc.item.SpitItem;
import net.mcreator.jigsawponosdlc.item.SovietSledgeItem;
import net.mcreator.jigsawponosdlc.item.SovietSickleItem;
import net.mcreator.jigsawponosdlc.item.SledgeDebugRMBItem;
import net.mcreator.jigsawponosdlc.item.SledgeDebugLMBItem;
import net.mcreator.jigsawponosdlc.item.SlavicTotemHammerItem;
import net.mcreator.jigsawponosdlc.item.SkewerTridentItem;
import net.mcreator.jigsawponosdlc.item.ShitStickGlaiveItem;
import net.mcreator.jigsawponosdlc.item.ShitIngotPlaceholderItem;
import net.mcreator.jigsawponosdlc.item.SexySledgehammerItem;
import net.mcreator.jigsawponosdlc.item.RoadSignHeavyAxeItem;
import net.mcreator.jigsawponosdlc.item.PyroItem;
import net.mcreator.jigsawponosdlc.item.PushkaPerdushkaItem;
import net.mcreator.jigsawponosdlc.item.PudgeItem;
import net.mcreator.jigsawponosdlc.item.ProperPigItem;
import net.mcreator.jigsawponosdlc.item.ProperItem;
import net.mcreator.jigsawponosdlc.item.ProperIncompleteItem;
import net.mcreator.jigsawponosdlc.item.ProperBadItem;
import net.mcreator.jigsawponosdlc.item.PonosthrowerNonAnalItem;
import net.mcreator.jigsawponosdlc.item.PonosthrowerItem;
import net.mcreator.jigsawponosdlc.item.PonosItem;
import net.mcreator.jigsawponosdlc.item.PizdoorHammerItem;
import net.mcreator.jigsawponosdlc.item.PirateCutlassItem;
import net.mcreator.jigsawponosdlc.item.PiggunItem;
import net.mcreator.jigsawponosdlc.item.PigSolutionFluidItem;
import net.mcreator.jigsawponosdlc.item.PigLiquidItem;
import net.mcreator.jigsawponosdlc.item.PigAppleItem;
import net.mcreator.jigsawponosdlc.item.PigAppleCorruptedItem;
import net.mcreator.jigsawponosdlc.item.PigAmmoItem;
import net.mcreator.jigsawponosdlc.item.PerdezhInBottleItem;
import net.mcreator.jigsawponosdlc.item.PerdezhDebugItem;
import net.mcreator.jigsawponosdlc.item.PaddleCoralBladeItem;
import net.mcreator.jigsawponosdlc.item.OpPiggunItem;
import net.mcreator.jigsawponosdlc.item.OakLauncherItem;
import net.mcreator.jigsawponosdlc.item.OakCanItem;
import net.mcreator.jigsawponosdlc.item.MaznyaEssenceItem;
import net.mcreator.jigsawponosdlc.item.LightoriumShardsItem;
import net.mcreator.jigsawponosdlc.item.LightoriumItem;
import net.mcreator.jigsawponosdlc.item.LeninStatueDebugItem;
import net.mcreator.jigsawponosdlc.item.KhuiniaItem;
import net.mcreator.jigsawponosdlc.item.IronCanItem;
import net.mcreator.jigsawponosdlc.item.InfectionSyringeItem;
import net.mcreator.jigsawponosdlc.item.HitlerStatueDebugItem;
import net.mcreator.jigsawponosdlc.item.HalfHeartOfTheSeaItem;
import net.mcreator.jigsawponosdlc.item.GorshcutlassItem;
import net.mcreator.jigsawponosdlc.item.GorshCrossItem;
import net.mcreator.jigsawponosdlc.item.GlassDebugItem;
import net.mcreator.jigsawponosdlc.item.FlintWreckerItem;
import net.mcreator.jigsawponosdlc.item.FartgasItem;
import net.mcreator.jigsawponosdlc.item.FacetedGlassFistItem;
import net.mcreator.jigsawponosdlc.item.ExtinguisherItem;
import net.mcreator.jigsawponosdlc.item.ExpensiveComponentItem;
import net.mcreator.jigsawponosdlc.item.ErshikTwinBladeItem;
import net.mcreator.jigsawponosdlc.item.EmptyBottleStaffItem;
import net.mcreator.jigsawponosdlc.item.EmptyBottleRoseRapierItem;
import net.mcreator.jigsawponosdlc.item.DickkatanaItem;
import net.mcreator.jigsawponosdlc.item.CoagulatedPigLiquidItem;
import net.mcreator.jigsawponosdlc.item.BrownBeardCutlassItem;
import net.mcreator.jigsawponosdlc.item.BotleOPricelItem;
import net.mcreator.jigsawponosdlc.item.BobrovuhaItem;
import net.mcreator.jigsawponosdlc.item.BeaverStaffItem;
import net.mcreator.jigsawponosdlc.item.BeaverStaffHoneyItem;
import net.mcreator.jigsawponosdlc.item.BeaverMassItem;
import net.mcreator.jigsawponosdlc.item.BeaverGunItem;
import net.mcreator.jigsawponosdlc.item.BeaverFistItem;
import net.mcreator.jigsawponosdlc.item.AutoForkItemItem;
import net.mcreator.jigsawponosdlc.item.AlcoholicItem;
import net.mcreator.jigsawponosdlc.item.AdvancedBeaverCollarItem;
import net.mcreator.jigsawponosdlc.JigsawPonosDlcMod;

public class JigsawPonosDlcModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, JigsawPonosDlcMod.MODID);
	public static final RegistryObject<Item> PONOSBLOCK = block(JigsawPonosDlcModBlocks.PONOSBLOCK, null);
	public static final RegistryObject<Item> PONOS = REGISTRY.register("ponos", () -> new PonosItem());
	public static final RegistryObject<Item> FART_PROJECTILE = REGISTRY.register("fart_projectile", () -> new PerdezhDebugItem());
	public static final RegistryObject<Item> PUSHKA_PERDUSHKA = REGISTRY.register("pushka_perdushka", () -> new PushkaPerdushkaItem());
	public static final RegistryObject<Item> PERDEZH_IN_BOTTLE = REGISTRY.register("perdezh_in_bottle", () -> new PerdezhInBottleItem());
	public static final RegistryObject<Item> PERDEZH_BLOCK = block(JigsawPonosDlcModBlocks.PERDEZH_BLOCK, null);
	public static final RegistryObject<Item> ADVANCED_BEAVER_COLLAR = REGISTRY.register("advanced_beaver_collar", () -> new AdvancedBeaverCollarItem());
	public static final RegistryObject<Item> SHIT_WOOFER = block(JigsawPonosDlcModBlocks.SHIT_WOOFER, JigsawPonosDlcModTabs.TAB_JIGSAW_PLUS);
	public static final RegistryObject<Item> PONOSTHROWER = REGISTRY.register("ponosthrower", () -> new PonosthrowerItem());
	public static final RegistryObject<Item> BRAWL_LEAVES = block(JigsawPonosDlcModBlocks.BRAWL_LEAVES, null);
	public static final RegistryObject<Item> FART_TURRET = block(JigsawPonosDlcModBlocks.FART_TURRET, JigsawPonosDlcModTabs.TAB_JIGSAW_PLUS);
	public static final RegistryObject<Item> DIAMOND_IRON_BLOCK = block(JigsawPonosDlcModBlocks.DIAMOND_IRON_BLOCK, JigsawPonosDlcModTabs.TAB_JIGSAW_PLUS);
	public static final RegistryObject<Item> PIGGUN = REGISTRY.register("piggun", () -> new PiggunItem());
	public static final RegistryObject<Item> PIG_AMMO = REGISTRY.register("pig_ammo", () -> new PigAmmoItem());
	public static final RegistryObject<Item> ZOMBIE_BEAVER_SPAWN_EGG = REGISTRY.register("zombie_beaver_spawn_egg",
			() -> new ForgeSpawnEggItem(JigsawPonosDlcModEntities.ZOMBIE_BEAVER, -16738048, -6724096, new Item.Properties().tab(JigsawPonosDlcModTabs.TAB_JIGSAW_PLUS)));
	public static final RegistryObject<Item> OP_PIGGUN = REGISTRY.register("op_piggun", () -> new OpPiggunItem());
	public static final RegistryObject<Item> BEAVER_GUN = REGISTRY.register("beaver_gun", () -> new BeaverGunItem());
	public static final RegistryObject<Item> FLINT_WRECKER = REGISTRY.register("flint_wrecker", () -> new FlintWreckerItem());
	public static final RegistryObject<Item> AUTO_FORK_ITEM = REGISTRY.register("auto_fork_item", () -> new AutoForkItemItem());
	public static final RegistryObject<Item> EXTINGUISHER = REGISTRY.register("extinguisher", () -> new ExtinguisherItem());
	public static final RegistryObject<Item> MAZNYA_ESSENCE = REGISTRY.register("maznya_essence", () -> new MaznyaEssenceItem());
	public static final RegistryObject<Item> SLEDGE_DEBUG_LMB = REGISTRY.register("sledge_debug_lmb", () -> new SledgeDebugLMBItem());
	public static final RegistryObject<Item> SEXY_SLEDGEHAMMER = REGISTRY.register("sexy_sledgehammer", () -> new SexySledgehammerItem());
	public static final RegistryObject<Item> SLEDGE_DEBUG_RMB = REGISTRY.register("sledge_debug_rmb", () -> new SledgeDebugRMBItem());
	public static final RegistryObject<Item> JAR = block(JigsawPonosDlcModBlocks.JAR, JigsawPonosDlcModTabs.TAB_JIGSAW_PLUS);
	public static final RegistryObject<Item> JAR_FILLED = block(JigsawPonosDlcModBlocks.JAR_FILLED, null);
	public static final RegistryObject<Item> BOBROVUHA_INFUSING = block(JigsawPonosDlcModBlocks.BOBROVUHA_INFUSING, null);
	public static final RegistryObject<Item> BOBROVUHA_DONE = block(JigsawPonosDlcModBlocks.BOBROVUHA_DONE, null);
	public static final RegistryObject<Item> BOBROVUHA = REGISTRY.register("bobrovuha", () -> new BobrovuhaItem());
	public static final RegistryObject<Item> WAND_OF_MASS_DESTRUCTION = REGISTRY.register("wand_of_mass_destruction", () -> new WandOfMassDestructionItem());
	public static final RegistryObject<Item> PERDEZHING_CLOUD_SPAWN_EGG = REGISTRY.register("perdezhing_cloud_spawn_egg", () -> new ForgeSpawnEggItem(JigsawPonosDlcModEntities.PERDEZHING_CLOUD, -1, -1, new Item.Properties().tab(null)));
	public static final RegistryObject<Item> UNIVERSE_PIG_SPAWN_EGG = REGISTRY.register("universe_pig_spawn_egg",
			() -> new ForgeSpawnEggItem(JigsawPonosDlcModEntities.UNIVERSE_PIG, -16751002, -52225, new Item.Properties().tab(JigsawPonosDlcModTabs.TAB_JIGSAW_PLUS)));
	public static final RegistryObject<Item> DICK_KATANA = REGISTRY.register("dick_katana", () -> new DickkatanaItem());
	public static final RegistryObject<Item> PIRATE_CUTLASS = REGISTRY.register("pirate_cutlass", () -> new PirateCutlassItem());
	public static final RegistryObject<Item> BEAVER_SPIDER_SPAWN_EGG = REGISTRY.register("beaver_spider_spawn_egg", () -> new ForgeSpawnEggItem(JigsawPonosDlcModEntities.BEAVER_SPIDER, -16777216, -6724096, new Item.Properties().tab(null)));
	public static final RegistryObject<Item> PONOSTHROWER_NON_ANAL = REGISTRY.register("ponosthrower_non_anal", () -> new PonosthrowerNonAnalItem());
	public static final RegistryObject<Item> BEAVER_FIRE = block(JigsawPonosDlcModBlocks.BEAVER_FIRE, null);
	public static final RegistryObject<Item> TELESCOPESUS = REGISTRY.register("telescopesus", () -> new TelescopesusItem());
	public static final RegistryObject<Item> ZOMBEAVER_SPAWNER_SPAWN_EGG = REGISTRY.register("zombeaver_spawner_spawn_egg",
			() -> new ForgeSpawnEggItem(JigsawPonosDlcModEntities.ZOMBEAVER_SPAWNER, -1, -1, new Item.Properties().tab(CreativeModeTab.TAB_BREWING)));
	public static final RegistryObject<Item> HALF_HEART_OF_THE_SEA = REGISTRY.register("half_heart_of_the_sea", () -> new HalfHeartOfTheSeaItem());
	public static final RegistryObject<Item> STONEBEAVER_SPAWN_EGG = REGISTRY.register("stonebeaver_spawn_egg",
			() -> new ForgeSpawnEggItem(JigsawPonosDlcModEntities.STONEBEAVER, -6710887, -3381760, new Item.Properties().tab(JigsawPonosDlcModTabs.TAB_JIGSAW_PLUS)));
	public static final RegistryObject<Item> MOSSELEPHANT_SPAWN_EGG = REGISTRY.register("mosselephant_spawn_egg",
			() -> new ForgeSpawnEggItem(JigsawPonosDlcModEntities.MOSSELEPHANT, -16751104, -65332, new Item.Properties().tab(JigsawPonosDlcModTabs.TAB_JIGSAW_PLUS)));
	public static final RegistryObject<Item> BEAVER_MASS_BUCKET = REGISTRY.register("beaver_mass_bucket", () -> new BeaverMassItem());
	public static final RegistryObject<Item> FARTGAS_BUCKET = REGISTRY.register("fartgas_bucket", () -> new FartgasItem());
	public static final RegistryObject<Item> PIG_SOLUTION_FLUID_BUCKET = REGISTRY.register("pig_solution_fluid_bucket", () -> new PigSolutionFluidItem());
	public static final RegistryObject<Item> IRON_CAN = REGISTRY.register("iron_can", () -> new IronCanItem());
	public static final RegistryObject<Item> SWEET_BREAD = REGISTRY.register("sweet_bread", () -> new SweetBreadItem());
	public static final RegistryObject<Item> SHIT_CUP = block(JigsawPonosDlcModBlocks.SHIT_CUP, JigsawPonosDlcModTabs.TAB_JIGSAW_PLUS);
	public static final RegistryObject<Item> SWEET_BREAD_RANGED = REGISTRY.register("sweet_bread_ranged", () -> new SweetBreadRangedItem());
	public static final RegistryObject<Item> BEAVER_FIST = REGISTRY.register("beaver_fist", () -> new BeaverFistItem());
	public static final RegistryObject<Item> SLAVIC_TOTEM_HAMMER = REGISTRY.register("slavic_totem_hammer", () -> new SlavicTotemHammerItem());
	public static final RegistryObject<Item> SLAVIC_TOTEM_UNCHARGED = block(JigsawPonosDlcModBlocks.SLAVIC_TOTEM_UNCHARGED, JigsawPonosDlcModTabs.TAB_JIGSAW_PLUS);
	public static final RegistryObject<Item> ZOMBIE_PUGALKA_SPAWN_EGG = REGISTRY.register("zombie_pugalka_spawn_egg", () -> new ForgeSpawnEggItem(JigsawPonosDlcModEntities.ZOMBIE_PUGALKA, -1, -1, new Item.Properties().tab(null)));
	public static final RegistryObject<Item> TAZIK_CHAKRAM = REGISTRY.register("tazik_chakram", () -> new TazikChakramItem());
	public static final RegistryObject<Item> TAZIK_CHAKRAM_FLOPPA = REGISTRY.register("tazik_chakram_floppa", () -> new TazikChakramFloppaItem());
	public static final RegistryObject<Item> TAZIK_KOSTYL_2_SPAWN_EGG = REGISTRY.register("tazik_kostyl_2_spawn_egg", () -> new ForgeSpawnEggItem(JigsawPonosDlcModEntities.TAZIK_KOSTYL_2, -1, -1, new Item.Properties().tab(null)));
	public static final RegistryObject<Item> TAZIK_KOSTYL_1 = REGISTRY.register("tazik_kostyl_1", () -> new TazikKostyl1Item());
	public static final RegistryObject<Item> FLOPPA_CUBE = block(JigsawPonosDlcModBlocks.FLOPPA_CUBE, JigsawPonosDlcModTabs.TAB_JIGSAW_PLUS);
	public static final RegistryObject<Item> PIG_BLOCK = block(JigsawPonosDlcModBlocks.PIG_BLOCK, JigsawPonosDlcModTabs.TAB_JIGSAW_PLUS);
	public static final RegistryObject<Item> CHISELED_PIG_BLOCK = block(JigsawPonosDlcModBlocks.CHISELED_PIG_BLOCK, JigsawPonosDlcModTabs.TAB_JIGSAW_PLUS);
	public static final RegistryObject<Item> EXPLOSIVE_PIG_BLOCK = block(JigsawPonosDlcModBlocks.EXPLOSIVE_PIG_BLOCK, JigsawPonosDlcModTabs.TAB_JIGSAW_PLUS);
	public static final RegistryObject<Item> SLIMY_PIG_BLOCK = block(JigsawPonosDlcModBlocks.SLIMY_PIG_BLOCK, JigsawPonosDlcModTabs.TAB_JIGSAW_PLUS);
	public static final RegistryObject<Item> PIG_LIQUID = REGISTRY.register("pig_liquid", () -> new PigLiquidItem());
	public static final RegistryObject<Item> COAGULATED_PIG_LIQUID = REGISTRY.register("coagulated_pig_liquid", () -> new CoagulatedPigLiquidItem());
	public static final RegistryObject<Item> PIG_EYE_BLOCK = block(JigsawPonosDlcModBlocks.PIG_EYE_BLOCK, JigsawPonosDlcModTabs.TAB_JIGSAW_PLUS);
	public static final RegistryObject<Item> LIGHTORIUM_SHARDS = REGISTRY.register("lightorium_shards", () -> new LightoriumShardsItem());
	public static final RegistryObject<Item> LIGHTORIUM = REGISTRY.register("lightorium", () -> new LightoriumItem());
	public static final RegistryObject<Item> PIG_LIGHT = block(JigsawPonosDlcModBlocks.PIG_LIGHT, JigsawPonosDlcModTabs.TAB_JIGSAW_PLUS);
	public static final RegistryObject<Item> PIG_MINION_SPAWN_EGG = REGISTRY.register("pig_minion_spawn_egg",
			() -> new ForgeSpawnEggItem(JigsawPonosDlcModEntities.PIG_MINION, -26215, -10027060, new Item.Properties().tab(JigsawPonosDlcModTabs.TAB_JIGSAW_PLUS)));
	public static final RegistryObject<Item> MEX_PIG_SPAWN_EGG = REGISTRY.register("mex_pig_spawn_egg",
			() -> new ForgeSpawnEggItem(JigsawPonosDlcModEntities.MEX_PIG, -26215, -6710887, new Item.Properties().tab(JigsawPonosDlcModTabs.TAB_JIGSAW_PLUS)));
	public static final RegistryObject<Item> PIG_EGG = block(JigsawPonosDlcModBlocks.PIG_EGG, JigsawPonosDlcModTabs.TAB_JIGSAW_PLUS);
	public static final RegistryObject<Item> INFECTION_SYRINGE = REGISTRY.register("infection_syringe", () -> new InfectionSyringeItem());
	public static final RegistryObject<Item> CYBER_PIG_BLOCK = block(JigsawPonosDlcModBlocks.CYBER_PIG_BLOCK, JigsawPonosDlcModTabs.TAB_JIGSAW_PLUS);
	public static final RegistryObject<Item> PIG_HOG_BLOCK = block(JigsawPonosDlcModBlocks.PIG_HOG_BLOCK, JigsawPonosDlcModTabs.TAB_JIGSAW_PLUS);
	public static final RegistryObject<Item> PIG_GEYSER = block(JigsawPonosDlcModBlocks.PIG_GEYSER, JigsawPonosDlcModTabs.TAB_JIGSAW_PLUS);
	public static final RegistryObject<Item> PIG_WOOD_WOOD = block(JigsawPonosDlcModBlocks.PIG_WOOD_WOOD, JigsawPonosDlcModTabs.TAB_JIGSAW_PLUS);
	public static final RegistryObject<Item> PIG_WOOD_LOG = block(JigsawPonosDlcModBlocks.PIG_WOOD_LOG, JigsawPonosDlcModTabs.TAB_JIGSAW_PLUS);
	public static final RegistryObject<Item> PIG_WOOD_PLANKS = block(JigsawPonosDlcModBlocks.PIG_WOOD_PLANKS, JigsawPonosDlcModTabs.TAB_JIGSAW_PLUS);
	public static final RegistryObject<Item> PIG_WOOD_LEAVES = block(JigsawPonosDlcModBlocks.PIG_WOOD_LEAVES, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> PIG_WOOD_STAIRS = block(JigsawPonosDlcModBlocks.PIG_WOOD_STAIRS, JigsawPonosDlcModTabs.TAB_JIGSAW_PLUS);
	public static final RegistryObject<Item> PIG_WOOD_SLAB = block(JigsawPonosDlcModBlocks.PIG_WOOD_SLAB, JigsawPonosDlcModTabs.TAB_JIGSAW_PLUS);
	public static final RegistryObject<Item> PIG_WOOD_FENCE = block(JigsawPonosDlcModBlocks.PIG_WOOD_FENCE, CreativeModeTab.TAB_DECORATIONS);
	public static final RegistryObject<Item> PIG_WOOD_FENCE_GATE = block(JigsawPonosDlcModBlocks.PIG_WOOD_FENCE_GATE, CreativeModeTab.TAB_REDSTONE);
	public static final RegistryObject<Item> PIG_WOOD_PRESSURE_PLATE = block(JigsawPonosDlcModBlocks.PIG_WOOD_PRESSURE_PLATE, CreativeModeTab.TAB_REDSTONE);
	public static final RegistryObject<Item> PIG_WOOD_BUTTON = block(JigsawPonosDlcModBlocks.PIG_WOOD_BUTTON, CreativeModeTab.TAB_REDSTONE);
	public static final RegistryObject<Item> ALCOHOLIC_CHESTPLATE = REGISTRY.register("alcoholic_chestplate", () -> new AlcoholicItem.Chestplate());
	public static final RegistryObject<Item> SKEWER_TRIDENT = REGISTRY.register("skewer_trident", () -> new SkewerTridentItem());
	public static final RegistryObject<Item> PIZDOOR_HAMMER = REGISTRY.register("pizdoor_hammer", () -> new PizdoorHammerItem());
	public static final RegistryObject<Item> PADDLE_CORAL_BLADE = REGISTRY.register("paddle_coral_blade", () -> new PaddleCoralBladeItem());
	public static final RegistryObject<Item> TEAPOT_MACE = block(JigsawPonosDlcModBlocks.TEAPOT_MACE, JigsawPonosDlcModTabs.TAB_JIGSAW_PLUS);
	public static final RegistryObject<Item> ERSHIK_TWIN_BLADE = REGISTRY.register("ershik_twin_blade", () -> new ErshikTwinBladeItem());
	public static final RegistryObject<Item> EMPTY_BOTTLE_STAFF = REGISTRY.register("empty_bottle_staff", () -> new EmptyBottleStaffItem());
	public static final RegistryObject<Item> EMPTY_BOTTLE_ROSE_RAPIER = REGISTRY.register("empty_bottle_rose_rapier", () -> new EmptyBottleRoseRapierItem());
	public static final RegistryObject<Item> GLASS_DEBUG = REGISTRY.register("glass_debug", () -> new GlassDebugItem());
	public static final RegistryObject<Item> FACETED_GLASS_FIST = REGISTRY.register("faceted_glass_fist", () -> new FacetedGlassFistItem());
	public static final RegistryObject<Item> ROAD_SIGN_HEAVY_AXE = REGISTRY.register("road_sign_heavy_axe", () -> new RoadSignHeavyAxeItem());
	public static final RegistryObject<Item> PUDGE_CHESTPLATE = REGISTRY.register("pudge_chestplate", () -> new PudgeItem.Chestplate());
	public static final RegistryObject<Item> SHIT_STICK_GLAIVE = REGISTRY.register("shit_stick_glaive", () -> new ShitStickGlaiveItem());
	public static final RegistryObject<Item> PROPER = REGISTRY.register("proper", () -> new ProperItem());
	public static final RegistryObject<Item> SHITTER = block(JigsawPonosDlcModBlocks.SHITTER, CreativeModeTab.TAB_BREWING);
	public static final RegistryObject<Item> OAK_CAN = REGISTRY.register("oak_can", () -> new OakCanItem());
	public static final RegistryObject<Item> OAK_LAUNCHER = REGISTRY.register("oak_launcher", () -> new OakLauncherItem());
	public static final RegistryObject<Item> PROPER_INCOMPLETE = REGISTRY.register("proper_incomplete", () -> new ProperIncompleteItem());
	public static final RegistryObject<Item> PROPER_BAD = REGISTRY.register("proper_bad", () -> new ProperBadItem());
	public static final RegistryObject<Item> VACUUM_CLEANER = REGISTRY.register("vacuum_cleaner", () -> new VacuumCleanerItem());
	public static final RegistryObject<Item> TEMP_CLOUD = block(JigsawPonosDlcModBlocks.TEMP_CLOUD, CreativeModeTab.TAB_BREWING);
	public static final RegistryObject<Item> PROPER_PIG = REGISTRY.register("proper_pig", () -> new ProperPigItem());
	public static final RegistryObject<Item> VC_DEBUG_PIG = REGISTRY.register("vc_debug_pig", () -> new VCDebugPigItem());
	public static final RegistryObject<Item> VC_DEBUG_BAD = REGISTRY.register("vc_debug_bad", () -> new VCDebugBadItem());
	public static final RegistryObject<Item> VC_DEBUG_MAIN = REGISTRY.register("vc_debug_main", () -> new VCDebugMainItem());
	public static final RegistryObject<Item> LEAVES_JIGSAWER = block(JigsawPonosDlcModBlocks.LEAVES_JIGSAWER, CreativeModeTab.TAB_BREWING);
	public static final RegistryObject<Item> PIG_SAPLING = block(JigsawPonosDlcModBlocks.PIG_SAPLING, JigsawPonosDlcModTabs.TAB_JIGSAW_PLUS);
	public static final RegistryObject<Item> CORRUPTED_PIG_SEEDS = block(JigsawPonosDlcModBlocks.CORRUPTED_PIG_SEEDS, CreativeModeTab.TAB_BREWING);
	public static final RegistryObject<Item> PIG_APPLE = REGISTRY.register("pig_apple", () -> new PigAppleItem());
	public static final RegistryObject<Item> PIG_APPLE_CORRUPTED = REGISTRY.register("pig_apple_corrupted", () -> new PigAppleCorruptedItem());
	public static final RegistryObject<Item> C_PIG_APPLE_BLOCK = block(JigsawPonosDlcModBlocks.C_PIG_APPLE_BLOCK, CreativeModeTab.TAB_BREWING);
	public static final RegistryObject<Item> TRUSI_LEGGINGS = REGISTRY.register("trusi_leggings", () -> new TrusiItem.Leggings());
	public static final RegistryObject<Item> BEAVER_STAFF = REGISTRY.register("beaver_staff", () -> new BeaverStaffItem());
	public static final RegistryObject<Item> BEAVER_STAFF_HONEY = REGISTRY.register("beaver_staff_honey", () -> new BeaverStaffHoneyItem());
	public static final RegistryObject<Item> GORSH_CROSS = REGISTRY.register("gorsh_cross", () -> new GorshCrossItem());
	public static final RegistryObject<Item> GORSHCUTLASS = REGISTRY.register("gorshcutlass", () -> new GorshcutlassItem());
	public static final RegistryObject<Item> EXPENSIVE_COMPONENT = REGISTRY.register("expensive_component", () -> new ExpensiveComponentItem());
	public static final RegistryObject<Item> BROWN_BEARD_CUTLASS = REGISTRY.register("brown_beard_cutlass", () -> new BrownBeardCutlassItem());
	public static final RegistryObject<Item> PYRO_HELMET = REGISTRY.register("pyro_helmet", () -> new PyroItem.Helmet());
	public static final RegistryObject<Item> KHUINIA = REGISTRY.register("khuinia", () -> new KhuiniaItem());
	public static final RegistryObject<Item> PRICEL_BOTTLE = block(JigsawPonosDlcModBlocks.PRICEL_BOTTLE, CreativeModeTab.TAB_BREWING);
	public static final RegistryObject<Item> BOTLE_O_PRICEL = REGISTRY.register("botle_o_pricel", () -> new BotleOPricelItem());
	public static final RegistryObject<Item> LENIN_STATUE_DEBUG = REGISTRY.register("lenin_statue_debug", () -> new LeninStatueDebugItem());
	public static final RegistryObject<Item> HITLER_STATUE_DEBUG = REGISTRY.register("hitler_statue_debug", () -> new HitlerStatueDebugItem());
	public static final RegistryObject<Item> LENIN_STATUE_SPAWN_EGG = REGISTRY.register("lenin_statue_spawn_egg",
			() -> new ForgeSpawnEggItem(JigsawPonosDlcModEntities.LENIN_STATUE, -1, -1, new Item.Properties().tab(JigsawPonosDlcModTabs.TAB_JIGSAW_PLUS)));
	public static final RegistryObject<Item> HITLER_STATUE_SPAWN_EGG = REGISTRY.register("hitler_statue_spawn_egg",
			() -> new ForgeSpawnEggItem(JigsawPonosDlcModEntities.HITLER_STATUE, -1, -1, new Item.Properties().tab(JigsawPonosDlcModTabs.TAB_JIGSAW_PLUS)));
	public static final RegistryObject<Item> SOVIET_SLEDGE = REGISTRY.register("soviet_sledge", () -> new SovietSledgeItem());
	public static final RegistryObject<Item> SHIT_INGOT_PLACEHOLDER = REGISTRY.register("shit_ingot_placeholder", () -> new ShitIngotPlaceholderItem());
	public static final RegistryObject<Item> SHIT_INGOR_BLOCK = block(JigsawPonosDlcModBlocks.SHIT_INGOR_BLOCK, JigsawPonosDlcModTabs.TAB_JIGSAW_PLUS);
	public static final RegistryObject<Item> SOVIET_SICKLE = REGISTRY.register("soviet_sickle", () -> new SovietSickleItem());
	public static final RegistryObject<Item> SPIT_HELMET = REGISTRY.register("spit_helmet", () -> new SpitItem.Helmet());
	public static final RegistryObject<Item> TEAPOT_BLACK = block(JigsawPonosDlcModBlocks.TEAPOT_BLACK, JigsawPonosDlcModTabs.TAB_JIGSAW_PLUS);

	private static RegistryObject<Item> block(RegistryObject<Block> block, CreativeModeTab tab) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties().tab(tab)));
	}
}
